### PR TITLE
feat: allow overriding instance profile name

### PR DESCRIPTION
**Pull request by MatteoJoliveau**
When creating provisioners outside of CDK having a friendlier Instance Profile name makes it easier to pass it around, compared to the ugly CDK-generated name.

## Example
Without override
```ts
new Karpenter(this, 'Karpenter', {
  cluster,
  vpc,
})

// instance profile name: instanceProfile: MyStackAFA747D8-KarpenterInstanceProfileCDDAB33E-Lh74yWBWUNIu
```

With override
```ts
new Karpenter(this, 'Karpenter', {
  cluster,
  vpc,
  instanceProfileName: 'my-instance-profile
})

// instance profile name: instanceProfile: my-instance-profile
```

### CODE REVIEW

**Comment by MatteoJoliveau** [comment]
@robertd sorry for the ping but I noticed my other pr (#31) is also still open. May I request your review on both? We need these features for our projects and would very much love helping maintain an existing project over forking/implementing our own

**Comment by robertd** [comment]
Thanks for the PR and sorry for the late response. I was out of the pocket for a while. I'll get cdk-karpenter project back on track soon.

**Comment by robertd** [comment]
@MatteoJoliveau Can you please pull the latest main and resubmit your PR? v2.0.0 introduced some breaking changes. Thanks!

**Comment by robertd** [comment]
@MatteoJoliveau Any updates on this PR?

**Pull request closed without merging**
